"""Add doctor fields to users table

Revision ID: 06e411825b9d
Revises: ff0c261ea5b5
Create Date: 2025-11-19 23:35:52.607439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e411825b9d'
down_revision = 'ff0c261ea5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('consultation_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('is_online')
        batch_op.drop_column('consultation_price')
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###
