"""Update medical record for dual images

Revision ID: 3a02308bcfa7
Revises: 795f7f159292
Create Date: 2025-11-22 10:47:43.828156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a02308bcfa7'
down_revision = '795f7f159292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eye_image_path', sa.String(length=255), nullable=True),
    sa.Column('nail_image_path', sa.String(length=255), nullable=True),
    sa.Column('hb_prediction', sa.Float(), nullable=False),
    sa.Column('symptoms_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_records')
    # ### end Alembic commands ###
