"""Update article table

Revision ID: 795f7f159292
Revises: 06e411825b9d
Create Date: 2025-11-22 10:40:53.380234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795f7f159292'
down_revision = '06e411825b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
