"""Update 2 medical record schema

Revision ID: a29f39cc54ff
Revises: 3a02308bcfa7
Create Date: 2025-11-22 11:22:11.033641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29f39cc54ff'
down_revision = '3a02308bcfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptoms_list', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_column('symptoms_list')

    # ### end Alembic commands ###
